### ISSUE TITLE
Hardcoded map frames

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/head_ref_ed_client#2]
https://github.com/tue-robotics/head_ref_ed_client/blob/master/src/head_ref_ed_client.cpp#L38
I don't know if this code is used, but I don't think those things should be hardcoded

**Comment by reinzor** [comment]
Why does this have prio?

-Rein

**Comment by MatthijsBurgh** [comment]
If it is not used, it doesn't have any prio. I was just looking through github and I found this.
